import gulp from 'gulp';
import ngConstant from 'gulp-ng-constant';
import config from './config';
import rename from 'gulp-rename';

export default function () {
  return ngConstant({
    name: 'app',
    constants: {
      VERSION: config.get('appVersion'),
      DEBUG_INFO_ENABLED: true
    },
    template: '    // DO NOT EDIT THIS FILE, EDIT THE GULP TASK NGCONSTANT SETTINGS INSTEAD WHICH GENERATES THIS FILE\n' +
    '    export default ()=> angular\n' +
    '        .module(\'<%- moduleName %>\')\n' +
    '<% constants.forEach(function(constant) { %>        .constant(\'<%- constant.name %>\', <%= constant.value %>)\n<% }) %>;\n',
    stream: true
  })
    .pipe(rename('version-constant.js'))
    .pipe(gulp.dest('app/shared/version'));
}
